config/routes.rb
Rails.application.routes.draw do

  root 'conversions#new'

  resources :conversions, only: [:new, :index, :create]

end

app/models/conversion.rb
class Conversion

  include ActiveModel::Model
  include Exchange::Rates
  
  attr_accessor :rate_at, :amount, :from_ccy, :to_ccy
  attr_reader :converted_amount

  validate :conversion_date
  validates :amount, numericality: {greater_than: 0}
  validates :from_ccy, :to_ccy, presence: true

  def initialize(attributes={})
    super
    @rate_at ||= Date.today
    @amount ||= 100.0
    @from_ccy ||= "GBP"
    @to_ccy ||= "GBP"
  end

  def conversion_date
    errors.add(:rate_at, "is not a date") unless rate_at.present? && is_date?(rate_at)
  end

  def convert
    rate = ExchangeRate.at(rate_at, from_ccy, to_ccy)
    @converted_amount = BigDecimal.new(amount.to_s) * rate
    true
  rescue NoRateError => e
    errors.add(:base, e.message)
    false
  end

  def attributes
    {rate_at: rate_at,
     amount: amount,
     from_ccy: from_ccy,
     to_ccy: to_ccy}
  end

  private

  def is_date?(value)
    return true if value.is_a? Date
    Date.parse(value) rescue false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController

  def index
    @conversion = Conversion.new(query_params)
    @conversion.convert
  end

  def new
    @conversion = Conversion.new
  end

  def create
    @conversion = Conversion.new(conversion_params)
    if @conversion.valid?
      redirect_to conversions_path(@conversion.attributes)
    else
      render :new
    end
  end

  private

  def conversion_params
    permitted(params.require(:conversion))
  end

  def query_params
    permitted(ActionController::Parameters.new(params))
  end

  def permitted(parameters)
    parameters.permit(:rate_at, :amount, :from_ccy, :to_ccy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversions_helper.rb
module ConversionsHelper

  def error_classes_for(object, attribute)
    "has-error has-feedback" if object.errors[attribute].any?
  end

  def error_text_for(object, attribute)
    if object.errors[attribute].any?
      content_tag(:span, object.errors[attribute].join(", "), class: "help-block") +
      content_tag(:span, "", class: "glyphicon glyphicon-remove form-control-feedback")
    end
  end

  def conversion_result(conversion)
    if conversion.errors[:base].empty?
      "#{number_with_precision(conversion.amount, precision: 2)} #{conversion.from_ccy} = #{number_with_precision(conversion.converted_amount)} #{conversion.to_ccy} on #{conversion.rate_at}"
    else
      conversion.errors[:base].join(", ")
    end
  end
end

app/views/conversions/index.html.erb
<h1><%= conversion_result(@conversion) %></h1>

<%= link_to "Convert another", new_conversion_path %>

app/views/conversions/new.html.erb
<div>
  <h1>FX-u-like</h1>
  <%= form_for @conversion, html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <div class="col-md-1">
        <%= f.label(:rate_at, "Date:", class: "control-label") %>
      </div>
      <div class="col-md-4 <%= error_classes_for(@conversion, :rate_at) %>">    	  
        <%= f.text_field(:rate_at, class: "form-control") %>
        <%= error_text_for(@conversion, :rate_at) %>  
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-1">
        <%= f.label(:amount, "Amount:", class: "control-label") %>
      </div>
      <div class="col-md-4 <%= error_classes_for(@conversion, :amount) %>">
        <%= f.text_field(:amount, class: "form-control") %>
        <%= error_text_for(@conversion, :amount) %>  
      </div>
      <div class="col-md-1">
        <%= f.label(:from_ccy, "From:", class: "control-label") %>
      </div>
      <div class="col-md-2">
        <%= f.select(:from_ccy, options_for_select(Exchange::Rates::ExchangeRate.currencies), {}, class: "form-control") %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-5 col-md-1">
        <%= f.label(:to_ccy, "To:", class: "control-label") %>
      </div>
      <div class="col-md-2">
        <%= f.select(:to_ccy, options_for_select(Exchange::Rates::ExchangeRate.currencies), {}, class: "form-control") %>
      </div>
    </div>
    <div class="form-group">
      <%= error_text_for(@conversion, :base) %>
    </div>
    <div class="form-group">
      <%= f.submit("Convert", class: "btn btn-primary") %>
    </div>
  <% end %>
</div>
<div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FxULike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>